// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

/* global window */
import type * as gax from 'google-gax';
import type {
  Callback,
  CallOptions,
  Descriptors,
  ClientOptions,
  PaginationCallback,
  GaxCall,
  LocationsClient,
  LocationProtos,
} from 'google-gax';
import {Transform} from 'stream';
import * as protos from '../../protos/protos';
import jsonProtos = require('../../protos/protos.json');
import {loggingUtils as logging, decodeAnyProtosInArray} from 'google-gax';

/**
 * Client JSON configuration object, loaded from
 * `src/v1beta4/blue_green_deployments_service_client_config.json`.
 * This file defines retry strategy and timeouts for all API methods in this library.
 */
import * as gapicConfig from './blue_green_deployments_service_client_config.json';
const version = require('../../../package.json').version;

/**
 *  Service for managing blue-green deployments.
 * @class
 * @memberof v1beta4
 */
export class BlueGreenDeploymentsServiceClient {
  private _terminated = false;
  private _opts: ClientOptions;
  private _providedCustomServicePath: boolean;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  private _universeDomain: string;
  private _servicePath: string;
  private _log = logging.log('sql');

  auth: gax.GoogleAuth;
  descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  warn: (code: string, message: string, warnType?: string) => void;
  innerApiCalls: {[name: string]: Function};
  locationsClient: LocationsClient;
  pathTemplates: {[name: string]: gax.PathTemplate};
  blueGreenDeploymentsServiceStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of BlueGreenDeploymentsServiceClient.
   *
   * @param {object} [options] - The configuration object.
   * The options accepted by the constructor are described in detail
   * in [this document](https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#creating-the-client-instance).
   * The common options are:
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://cloud.google.com/docs/authentication/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   * @param {gax.ClientConfig} [options.clientConfig] - Client configuration override.
   *     Follows the structure of {@link gapicConfig}.
   * @param {boolean} [options.fallback] - Use HTTP/1.1 REST mode.
   *     For more information, please check the
   *     {@link https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#http11-rest-api-mode documentation}.
   * @param {gax} [gaxInstance]: loaded instance of `google-gax`. Useful if you
   *     need to avoid loading the default gRPC version and want to use the fallback
   *     HTTP implementation. Load only fallback version and pass it to the constructor:
   *     ```
   *     const gax = require('google-gax/build/src/fallback'); // avoids loading google-gax with gRPC
   *     const client = new BlueGreenDeploymentsServiceClient({fallback: true}, gax);
   *     ```
   */
  constructor(
    opts?: ClientOptions,
    gaxInstance?: typeof gax | typeof gax.fallback,
  ) {
    // Ensure that options include all the required fields.
    const staticMembers = this
      .constructor as typeof BlueGreenDeploymentsServiceClient;
    if (
      opts?.universe_domain &&
      opts?.universeDomain &&
      opts?.universe_domain !== opts?.universeDomain
    ) {
      throw new Error(
        'Please set either universe_domain or universeDomain, but not both.',
      );
    }
    const universeDomainEnvVar =
      typeof process === 'object' && typeof process.env === 'object'
        ? process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN']
        : undefined;
    this._universeDomain =
      opts?.universeDomain ??
      opts?.universe_domain ??
      universeDomainEnvVar ??
      'googleapis.com';
    this._servicePath = 'sqladmin.' + this._universeDomain;
    const servicePath =
      opts?.servicePath || opts?.apiEndpoint || this._servicePath;
    this._providedCustomServicePath = !!(
      opts?.servicePath || opts?.apiEndpoint
    );
    const port = opts?.port || staticMembers.port;
    const clientConfig = opts?.clientConfig ?? {};
    const fallback =
      opts?.fallback ??
      (typeof window !== 'undefined' && typeof window?.fetch === 'function');
    opts = Object.assign({servicePath, port, clientConfig, fallback}, opts);

    // Request numeric enum values if REST transport is used.
    opts.numericEnums = true;

    // If scopes are unset in options and we're connecting to a non-default endpoint, set scopes just in case.
    if (servicePath !== this._servicePath && !('scopes' in opts)) {
      opts['scopes'] = staticMembers.scopes;
    }

    // Load google-gax module synchronously if needed
    if (!gaxInstance) {
      gaxInstance = require('google-gax') as typeof gax;
    }

    // Choose either gRPC or proto-over-HTTP implementation of google-gax.
    this._gaxModule = opts.fallback ? gaxInstance.fallback : gaxInstance;

    // Create a `gaxGrpc` object, with any grpc-specific options sent to the client.
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = this._gaxGrpc.auth as gax.GoogleAuth;

    // Set useJWTAccessWithScope on the auth object.
    this.auth.useJWTAccessWithScope = true;

    // Set defaultServicePath on the auth object.
    this.auth.defaultServicePath = this._servicePath;

    // Set the default scopes in auth client if needed.
    if (servicePath === this._servicePath) {
      this.auth.defaultScopes = staticMembers.scopes;
    }
    this.locationsClient = new this._gaxModule.LocationsClient(
      this._gaxGrpc,
      opts,
    );

    // Determine the client header string.
    const clientHeader = [`gax/${this._gaxModule.version}`, `gapic/${version}`];
    if (typeof process === 'object' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    } else {
      clientHeader.push(`rest/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    this._protos = this._gaxGrpc.loadProtoJSON(jsonProtos);

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this.pathTemplates = {
      backupPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/backups/{backup}',
      ),
      blueGreenDeploymentPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/blueGreenDeployments/{blue_green_deployment}',
      ),
      locationPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}',
      ),
      projectPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}',
      ),
    };

    // Some of the methods on this service return "paged" results,
    // (e.g. 50 results at a time, with tokens to get subsequent
    // pages). Denote the keys used for pagination and results.
    this.descriptors.page = {
      listBlueGreenDeployments: new this._gaxModule.PageDescriptor(
        'pageToken',
        'nextPageToken',
        'blueGreenDeployments',
      ),
    };

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
      'google.cloud.sql.v1beta4.BlueGreenDeploymentsService',
      gapicConfig as gax.ClientConfig,
      opts.clientConfig || {},
      {'x-goog-api-client': clientHeader.join(' ')},
    );

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this.innerApiCalls = {};

    // Add a warn function to the client constructor so it can be easily tested.
    this.warn = this._gaxModule.warn;
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.blueGreenDeploymentsServiceStub) {
      return this.blueGreenDeploymentsServiceStub;
    }

    // Put together the "service stub" for
    // google.cloud.sql.v1beta4.BlueGreenDeploymentsService.
    this.blueGreenDeploymentsServiceStub = this._gaxGrpc.createStub(
      this._opts.fallback
        ? (this._protos as protobuf.Root).lookupService(
            'google.cloud.sql.v1beta4.BlueGreenDeploymentsService',
          )
        : // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this._protos as any).google.cloud.sql.v1beta4
            .BlueGreenDeploymentsService,
      this._opts,
      this._providedCustomServicePath,
    ) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const blueGreenDeploymentsServiceStubMethods = [
      'createBlueGreenDeployment',
      'getBlueGreenDeployment',
      'listBlueGreenDeployments',
      'switchoverBlueGreenDeployment',
      'deleteBlueGreenDeployment',
    ];
    for (const methodName of blueGreenDeploymentsServiceStubMethods) {
      const callPromise = this.blueGreenDeploymentsServiceStub.then(
        stub =>
          (...args: Array<{}>) => {
            if (this._terminated) {
              return Promise.reject('The client has already been closed.');
            }
            const func = stub[methodName];
            return func.apply(stub, args);
          },
        (err: Error | null | undefined) => () => {
          throw err;
        },
      );

      const descriptor = this.descriptors.page[methodName] || undefined;
      const apiCall = this._gaxModule.createApiCall(
        callPromise,
        this._defaults[methodName],
        descriptor,
        this._opts.fallback,
      );

      this.innerApiCalls[methodName] = apiCall;
    }

    return this.blueGreenDeploymentsServiceStub;
  }

  /**
   * The DNS address for this API service.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get servicePath() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static servicePath is deprecated, please use the instance method instead.',
        'DeprecationWarning',
      );
    }
    return 'sqladmin.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get apiEndpoint() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static apiEndpoint is deprecated, please use the instance method instead.',
        'DeprecationWarning',
      );
    }
    return 'sqladmin.googleapis.com';
  }

  /**
   * The DNS address for this API service.
   * @returns {string} The DNS address for this service.
   */
  get apiEndpoint() {
    return this._servicePath;
  }

  get universeDomain() {
    return this._universeDomain;
  }

  /**
   * The port for this API service.
   * @returns {number} The default port for this service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   * @returns {string[]} List of default scopes.
   */
  static get scopes() {
    return [
      'https://www.googleapis.com/auth/cloud-platform',
      'https://www.googleapis.com/auth/sqlservice.admin',
    ];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @returns {Promise} A promise that resolves to string containing the project ID.
   */
  getProjectId(
    callback?: Callback<string, undefined, undefined>,
  ): Promise<string> | void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  /**
   * Creates a blue-green deployment under a given project and location. This
   * deployment provisions a synchronized green environment (target instance)
   * from a blue production environment (source instance), facilitating updates
   * like major version upgrades on the green instance without impacting the
   * blue instance.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. The parent resource where this blue-green deployment will be
   *   created. Format: projects/{project}/locations/{location}
   * @param {string} request.blueGreenDeploymentId
   *   Required. The ID to use for the blue-green deployment, which will become
   *   the final component of the deployment's resource name.
   * @param {google.cloud.sql.v1beta4.BlueGreenDeployment} request.blueGreenDeployment
   *   Required. The `BlueGreenDeployment` resource to create.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.Operation|Operation}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/blue_green_deployments_service.create_blue_green_deployment.js</caption>
   * region_tag:sqladmin_v1beta4_generated_BlueGreenDeploymentsService_CreateBlueGreenDeployment_async
   */
  createBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  createBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  createBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  createBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        parent: request.parent ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('createBlueGreenDeployment request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('createBlueGreenDeployment response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .createBlueGreenDeployment(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IOperation,
          (
            | protos.google.cloud.sql.v1beta4.ICreateBlueGreenDeploymentRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('createBlueGreenDeployment response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }
  /**
   * Retrieves a blue-green deployment resource under a given project and
   * location.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the blue-green deployment to retrieve.
   *   Format:
   *   projects/{project}/locations/{location}/blueGreenDeployments/{blue_green_deployment}
   * @param {google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest.BlueGreenDeploymentView} [request.view]
   *   Optional. Specifies whether to return the basic or detailed view of the
   *   resource in the response.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.BlueGreenDeployment|BlueGreenDeployment}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/blue_green_deployments_service.get_blue_green_deployment.js</caption>
   * region_tag:sqladmin_v1beta4_generated_BlueGreenDeploymentsService_GetBlueGreenDeployment_async
   */
  getBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
      (
        | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  getBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
      | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  getBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
      | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  getBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
          | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
      | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
      (
        | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        name: request.name ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('getBlueGreenDeployment request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
          | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('getBlueGreenDeployment response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .getBlueGreenDeployment(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IBlueGreenDeployment,
          (
            | protos.google.cloud.sql.v1beta4.IGetBlueGreenDeploymentRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('getBlueGreenDeployment response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }
  /**
   * Switches over to green instance for a blue-green deployment.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the blue-green deployment to switch over.
   *   Format:
   *   projects/{project}/locations/{location}/blueGreenDeployments/{blue_green_deployment}
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.Operation|Operation}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/blue_green_deployments_service.switchover_blue_green_deployment.js</caption>
   * region_tag:sqladmin_v1beta4_generated_BlueGreenDeploymentsService_SwitchoverBlueGreenDeployment_async
   */
  switchoverBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  switchoverBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  switchoverBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  switchoverBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        name: request.name ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('switchoverBlueGreenDeployment request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('switchoverBlueGreenDeployment response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .switchoverBlueGreenDeployment(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IOperation,
          (
            | protos.google.cloud.sql.v1beta4.ISwitchoverBlueGreenDeploymentRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('switchoverBlueGreenDeployment response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }
  /**
   * Deletes a blue-green deployment, including metadata and underlying
   * resources based on the deployment state. If issued before switchover,
   * this deletes the green instance. If issued after switchover, this deletes
   * the old blue instance (source instance) if the `delete_old_source` field
   * in the request is set to true.
   * All blue-green deployment metadata is permanently deleted.
   * Resources deleted as a result of this operation are no longer accessible
   * and can't be restored.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the blue-green deployment to delete.
   *   Format:
   *   projects/{project}/locations/{location}/blueGreenDeployments/{blue_green_deployment}
   * @param {boolean} [request.deleteOldSource]
   *   Optional. If set to true, and the switchover is complete, this deletes the
   *   old source instance along with the deployment.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.Operation|Operation}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/blue_green_deployments_service.delete_blue_green_deployment.js</caption>
   * region_tag:sqladmin_v1beta4_generated_BlueGreenDeploymentsService_DeleteBlueGreenDeployment_async
   */
  deleteBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  deleteBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  deleteBlueGreenDeployment(
    request: protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  deleteBlueGreenDeployment(
    request?: protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        name: request.name ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('deleteBlueGreenDeployment request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('deleteBlueGreenDeployment response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .deleteBlueGreenDeployment(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IOperation,
          (
            | protos.google.cloud.sql.v1beta4.IDeleteBlueGreenDeploymentRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('deleteBlueGreenDeployment response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }

  /**
   * Lists blue-green deployments under a given project.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. The parent resource whose blue-green deployments are to be
   *   listed. Format: projects/{project}/locations/{location}
   * @param {number} [request.pageSize]
   *   Optional. The maximum number of deployments to return.
   * @param {string} [request.pageToken]
   *   Optional. A page token, received from a previous `ListBlueGreenDeployments`
   *   call. Provide this to retrieve the subsequent page.
   * @param {string} [request.filter]
   *   Optional. A filter expression that filters the results.
   * @param {string} [request.orderBy]
   *   Optional. A comma-separated list of fields to order the results by.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is Array of {@link protos.google.cloud.sql.v1beta4.BlueGreenDeployment|BlueGreenDeployment}.
   *   The client library will perform auto-pagination by default: it will call the API as many
   *   times as needed and will merge results from all the pages into this array.
   *   Note that it can affect your quota.
   *   We recommend using `listBlueGreenDeploymentsAsync()`
   *   method described below for async iteration which you can stop as needed.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
   *   for more details and examples.
   */
  listBlueGreenDeployments(
    request?: protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment[],
      protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest | null,
      protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse,
    ]
  >;
  listBlueGreenDeployments(
    request: protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
    options: CallOptions,
    callback: PaginationCallback<
      protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
      | protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse
      | null
      | undefined,
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment
    >,
  ): void;
  listBlueGreenDeployments(
    request: protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
    callback: PaginationCallback<
      protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
      | protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse
      | null
      | undefined,
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment
    >,
  ): void;
  listBlueGreenDeployments(
    request?: protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
    optionsOrCallback?:
      | CallOptions
      | PaginationCallback<
          protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
          | protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse
          | null
          | undefined,
          protos.google.cloud.sql.v1beta4.IBlueGreenDeployment
        >,
    callback?: PaginationCallback<
      protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
      | protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse
      | null
      | undefined,
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IBlueGreenDeployment[],
      protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest | null,
      protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        parent: request.parent ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    const wrappedCallback:
      | PaginationCallback<
          protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
          | protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse
          | null
          | undefined,
          protos.google.cloud.sql.v1beta4.IBlueGreenDeployment
        >
      | undefined = callback
      ? (error, values, nextPageRequest, rawResponse) => {
          this._log.info('listBlueGreenDeployments values %j', values);
          callback!(error, values, nextPageRequest, rawResponse); // We verified callback above.
        }
      : undefined;
    this._log.info('listBlueGreenDeployments request %j', request);
    return this.innerApiCalls
      .listBlueGreenDeployments(request, options, wrappedCallback)
      ?.then(
        ([response, input, output]: [
          protos.google.cloud.sql.v1beta4.IBlueGreenDeployment[],
          protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest | null,
          protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsResponse,
        ]) => {
          this._log.info('listBlueGreenDeployments values %j', response);
          return [response, input, output];
        },
      );
  }

  /**
   * Equivalent to `listBlueGreenDeployments`, but returns a NodeJS Stream object.
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. The parent resource whose blue-green deployments are to be
   *   listed. Format: projects/{project}/locations/{location}
   * @param {number} [request.pageSize]
   *   Optional. The maximum number of deployments to return.
   * @param {string} [request.pageToken]
   *   Optional. A page token, received from a previous `ListBlueGreenDeployments`
   *   call. Provide this to retrieve the subsequent page.
   * @param {string} [request.filter]
   *   Optional. A filter expression that filters the results.
   * @param {string} [request.orderBy]
   *   Optional. A comma-separated list of fields to order the results by.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Stream}
   *   An object stream which emits an object representing {@link protos.google.cloud.sql.v1beta4.BlueGreenDeployment|BlueGreenDeployment} on 'data' event.
   *   The client library will perform auto-pagination by default: it will call the API as many
   *   times as needed. Note that it can affect your quota.
   *   We recommend using `listBlueGreenDeploymentsAsync()`
   *   method described below for async iteration which you can stop as needed.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
   *   for more details and examples.
   */
  listBlueGreenDeploymentsStream(
    request?: protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
    options?: CallOptions,
  ): Transform {
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        parent: request.parent ?? '',
      });
    const defaultCallSettings = this._defaults['listBlueGreenDeployments'];
    const callSettings = defaultCallSettings.merge(options);
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('listBlueGreenDeployments stream %j', request);
    return this.descriptors.page.listBlueGreenDeployments.createStream(
      this.innerApiCalls.listBlueGreenDeployments as GaxCall,
      request,
      callSettings,
    );
  }

  /**
   * Equivalent to `listBlueGreenDeployments`, but returns an iterable object.
   *
   * `for`-`await`-`of` syntax is used with the iterable to get response elements on-demand.
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.parent
   *   Required. The parent resource whose blue-green deployments are to be
   *   listed. Format: projects/{project}/locations/{location}
   * @param {number} [request.pageSize]
   *   Optional. The maximum number of deployments to return.
   * @param {string} [request.pageToken]
   *   Optional. A page token, received from a previous `ListBlueGreenDeployments`
   *   call. Provide this to retrieve the subsequent page.
   * @param {string} [request.filter]
   *   Optional. A filter expression that filters the results.
   * @param {string} [request.orderBy]
   *   Optional. A comma-separated list of fields to order the results by.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Object}
   *   An iterable Object that allows {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols | async iteration }.
   *   When you iterate the returned iterable, each element will be an object representing
   *   {@link protos.google.cloud.sql.v1beta4.BlueGreenDeployment|BlueGreenDeployment}. The API will be called under the hood as needed, once per the page,
   *   so you can stop the iteration when you don't need more results.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/blue_green_deployments_service.list_blue_green_deployments.js</caption>
   * region_tag:sqladmin_v1beta4_generated_BlueGreenDeploymentsService_ListBlueGreenDeployments_async
   */
  listBlueGreenDeploymentsAsync(
    request?: protos.google.cloud.sql.v1beta4.IListBlueGreenDeploymentsRequest,
    options?: CallOptions,
  ): AsyncIterable<protos.google.cloud.sql.v1beta4.IBlueGreenDeployment> {
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        parent: request.parent ?? '',
      });
    const defaultCallSettings = this._defaults['listBlueGreenDeployments'];
    const callSettings = defaultCallSettings.merge(options);
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('listBlueGreenDeployments iterate %j', request);
    return this.descriptors.page.listBlueGreenDeployments.asyncIterate(
      this.innerApiCalls['listBlueGreenDeployments'] as GaxCall,
      request as {},
      callSettings,
    ) as AsyncIterable<protos.google.cloud.sql.v1beta4.IBlueGreenDeployment>;
  }

  /**
   * Gets information about a location.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Resource name for the location.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html | CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link google.cloud.location.Location | Location}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example
   * ```
   * const [response] = await client.getLocation(request);
   * ```
   */
  getLocation(
    request: LocationProtos.google.cloud.location.IGetLocationRequest,
    options?:
      | gax.CallOptions
      | Callback<
          LocationProtos.google.cloud.location.ILocation,
          | LocationProtos.google.cloud.location.IGetLocationRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      LocationProtos.google.cloud.location.ILocation,
      | LocationProtos.google.cloud.location.IGetLocationRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<LocationProtos.google.cloud.location.ILocation> {
    return this.locationsClient.getLocation(request, options, callback);
  }
  /**
   * Lists information about the supported locations for this service. Returns an iterable object.
   *
   * `for`-`await`-`of` syntax is used with the iterable to get response elements on-demand.
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   The resource that owns the locations collection, if applicable.
   * @param {string} request.filter
   *   The standard list filter.
   * @param {number} request.pageSize
   *   The standard list page size.
   * @param {string} request.pageToken
   *   The standard list page token.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Object}
   *   An iterable Object that allows {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols | async iteration }.
   *   When you iterate the returned iterable, each element will be an object representing
   *   {@link google.cloud.location.Location | Location}. The API will be called under the hood as needed, once per the page,
   *   so you can stop the iteration when you don't need more results.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
   *   for more details and examples.
   * @example
   * ```
   * const iterable = client.listLocationsAsync(request);
   * for await (const response of iterable) {
   *   // process response
   * }
   * ```
   */
  listLocationsAsync(
    request: LocationProtos.google.cloud.location.IListLocationsRequest,
    options?: CallOptions,
  ): AsyncIterable<LocationProtos.google.cloud.location.ILocation> {
    return this.locationsClient.listLocationsAsync(request, options);
  }

  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified backup resource name string.
   *
   * @param {string} project
   * @param {string} backup
   * @returns {string} Resource name string.
   */
  backupPath(project: string, backup: string) {
    return this.pathTemplates.backupPathTemplate.render({
      project: project,
      backup: backup,
    });
  }

  /**
   * Parse the project from Backup resource.
   *
   * @param {string} backupName
   *   A fully-qualified path representing Backup resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromBackupName(backupName: string) {
    return this.pathTemplates.backupPathTemplate.match(backupName).project;
  }

  /**
   * Parse the backup from Backup resource.
   *
   * @param {string} backupName
   *   A fully-qualified path representing Backup resource.
   * @returns {string} A string representing the backup.
   */
  matchBackupFromBackupName(backupName: string) {
    return this.pathTemplates.backupPathTemplate.match(backupName).backup;
  }

  /**
   * Return a fully-qualified blueGreenDeployment resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} blue_green_deployment
   * @returns {string} Resource name string.
   */
  blueGreenDeploymentPath(
    project: string,
    location: string,
    blueGreenDeployment: string,
  ) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.render({
      project: project,
      location: location,
      blue_green_deployment: blueGreenDeployment,
    });
  }

  /**
   * Parse the project from BlueGreenDeployment resource.
   *
   * @param {string} blueGreenDeploymentName
   *   A fully-qualified path representing BlueGreenDeployment resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromBlueGreenDeploymentName(blueGreenDeploymentName: string) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.match(
      blueGreenDeploymentName,
    ).project;
  }

  /**
   * Parse the location from BlueGreenDeployment resource.
   *
   * @param {string} blueGreenDeploymentName
   *   A fully-qualified path representing BlueGreenDeployment resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromBlueGreenDeploymentName(blueGreenDeploymentName: string) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.match(
      blueGreenDeploymentName,
    ).location;
  }

  /**
   * Parse the blue_green_deployment from BlueGreenDeployment resource.
   *
   * @param {string} blueGreenDeploymentName
   *   A fully-qualified path representing BlueGreenDeployment resource.
   * @returns {string} A string representing the blue_green_deployment.
   */
  matchBlueGreenDeploymentFromBlueGreenDeploymentName(
    blueGreenDeploymentName: string,
  ) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.match(
      blueGreenDeploymentName,
    ).blue_green_deployment;
  }

  /**
   * Return a fully-qualified location resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @returns {string} Resource name string.
   */
  locationPath(project: string, location: string) {
    return this.pathTemplates.locationPathTemplate.render({
      project: project,
      location: location,
    });
  }

  /**
   * Parse the project from Location resource.
   *
   * @param {string} locationName
   *   A fully-qualified path representing Location resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromLocationName(locationName: string) {
    return this.pathTemplates.locationPathTemplate.match(locationName).project;
  }

  /**
   * Parse the location from Location resource.
   *
   * @param {string} locationName
   *   A fully-qualified path representing Location resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromLocationName(locationName: string) {
    return this.pathTemplates.locationPathTemplate.match(locationName).location;
  }

  /**
   * Return a fully-qualified project resource name string.
   *
   * @param {string} project
   * @returns {string} Resource name string.
   */
  projectPath(project: string) {
    return this.pathTemplates.projectPathTemplate.render({
      project: project,
    });
  }

  /**
   * Parse the project from Project resource.
   *
   * @param {string} projectName
   *   A fully-qualified path representing Project resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromProjectName(projectName: string) {
    return this.pathTemplates.projectPathTemplate.match(projectName).project;
  }

  /**
   * Terminate the gRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   * @returns {Promise} A promise that resolves when the client is closed.
   */
  close(): Promise<void> {
    if (this.blueGreenDeploymentsServiceStub && !this._terminated) {
      return this.blueGreenDeploymentsServiceStub.then(stub => {
        this._log.info('ending gRPC channel');
        this._terminated = true;
        stub.close();
        this.locationsClient.close().catch(err => {
          throw err;
        });
      });
    }
    return Promise.resolve();
  }
}
