// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

/* global window */
import type * as gax from 'google-gax';
import type {
  Callback,
  CallOptions,
  Descriptors,
  ClientOptions,
  LocationsClient,
  LocationProtos,
} from 'google-gax';

import * as protos from '../../protos/protos';
import jsonProtos = require('../../protos/protos.json');
import {loggingUtils as logging, decodeAnyProtosInArray} from 'google-gax';

/**
 * Client JSON configuration object, loaded from
 * `src/v1beta4/sql_workload_captures_service_client_config.json`.
 * This file defines retry strategy and timeouts for all API methods in this library.
 */
import * as gapicConfig from './sql_workload_captures_service_client_config.json';
const version = require('../../../package.json').version;

/**
 *  Cloud SQL Workload Captures service.
 * @class
 * @memberof v1beta4
 */
export class SqlWorkloadCapturesServiceClient {
  private _terminated = false;
  private _opts: ClientOptions;
  private _providedCustomServicePath: boolean;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  private _universeDomain: string;
  private _servicePath: string;
  private _log = logging.log('sql');

  auth: gax.GoogleAuth;
  descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  warn: (code: string, message: string, warnType?: string) => void;
  innerApiCalls: {[name: string]: Function};
  locationsClient: LocationsClient;
  pathTemplates: {[name: string]: gax.PathTemplate};
  sqlWorkloadCapturesServiceStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of SqlWorkloadCapturesServiceClient.
   *
   * @param {object} [options] - The configuration object.
   * The options accepted by the constructor are described in detail
   * in [this document](https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#creating-the-client-instance).
   * The common options are:
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://cloud.google.com/docs/authentication/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   * @param {gax.ClientConfig} [options.clientConfig] - Client configuration override.
   *     Follows the structure of {@link gapicConfig}.
   * @param {boolean} [options.fallback] - Use HTTP/1.1 REST mode.
   *     For more information, please check the
   *     {@link https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#http11-rest-api-mode documentation}.
   * @param {gax} [gaxInstance]: loaded instance of `google-gax`. Useful if you
   *     need to avoid loading the default gRPC version and want to use the fallback
   *     HTTP implementation. Load only fallback version and pass it to the constructor:
   *     ```
   *     const gax = require('google-gax/build/src/fallback'); // avoids loading google-gax with gRPC
   *     const client = new SqlWorkloadCapturesServiceClient({fallback: true}, gax);
   *     ```
   */
  constructor(
    opts?: ClientOptions,
    gaxInstance?: typeof gax | typeof gax.fallback,
  ) {
    // Ensure that options include all the required fields.
    const staticMembers = this
      .constructor as typeof SqlWorkloadCapturesServiceClient;
    if (
      opts?.universe_domain &&
      opts?.universeDomain &&
      opts?.universe_domain !== opts?.universeDomain
    ) {
      throw new Error(
        'Please set either universe_domain or universeDomain, but not both.',
      );
    }
    const universeDomainEnvVar =
      typeof process === 'object' && typeof process.env === 'object'
        ? process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN']
        : undefined;
    this._universeDomain =
      opts?.universeDomain ??
      opts?.universe_domain ??
      universeDomainEnvVar ??
      'googleapis.com';
    this._servicePath = 'sqladmin.' + this._universeDomain;
    const servicePath =
      opts?.servicePath || opts?.apiEndpoint || this._servicePath;
    this._providedCustomServicePath = !!(
      opts?.servicePath || opts?.apiEndpoint
    );
    const port = opts?.port || staticMembers.port;
    const clientConfig = opts?.clientConfig ?? {};
    const fallback =
      opts?.fallback ??
      (typeof window !== 'undefined' && typeof window?.fetch === 'function');
    opts = Object.assign({servicePath, port, clientConfig, fallback}, opts);

    // Request numeric enum values if REST transport is used.
    opts.numericEnums = true;

    // If scopes are unset in options and we're connecting to a non-default endpoint, set scopes just in case.
    if (servicePath !== this._servicePath && !('scopes' in opts)) {
      opts['scopes'] = staticMembers.scopes;
    }

    // Load google-gax module synchronously if needed
    if (!gaxInstance) {
      gaxInstance = require('google-gax') as typeof gax;
    }

    // Choose either gRPC or proto-over-HTTP implementation of google-gax.
    this._gaxModule = opts.fallback ? gaxInstance.fallback : gaxInstance;

    // Create a `gaxGrpc` object, with any grpc-specific options sent to the client.
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = this._gaxGrpc.auth as gax.GoogleAuth;

    // Set useJWTAccessWithScope on the auth object.
    this.auth.useJWTAccessWithScope = true;

    // Set defaultServicePath on the auth object.
    this.auth.defaultServicePath = this._servicePath;

    // Set the default scopes in auth client if needed.
    if (servicePath === this._servicePath) {
      this.auth.defaultScopes = staticMembers.scopes;
    }
    this.locationsClient = new this._gaxModule.LocationsClient(
      this._gaxGrpc,
      opts,
    );

    // Determine the client header string.
    const clientHeader = [`gax/${this._gaxModule.version}`, `gapic/${version}`];
    if (typeof process === 'object' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    } else {
      clientHeader.push(`rest/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    this._protos = this._gaxGrpc.loadProtoJSON(jsonProtos);

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this.pathTemplates = {
      backupPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/backups/{backup}',
      ),
      blueGreenDeploymentPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/blueGreenDeployments/{blue_green_deployment}',
      ),
    };

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
      'google.cloud.sql.v1beta4.SqlWorkloadCapturesService',
      gapicConfig as gax.ClientConfig,
      opts.clientConfig || {},
      {'x-goog-api-client': clientHeader.join(' ')},
    );

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this.innerApiCalls = {};

    // Add a warn function to the client constructor so it can be easily tested.
    this.warn = this._gaxModule.warn;
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.sqlWorkloadCapturesServiceStub) {
      return this.sqlWorkloadCapturesServiceStub;
    }

    // Put together the "service stub" for
    // google.cloud.sql.v1beta4.SqlWorkloadCapturesService.
    this.sqlWorkloadCapturesServiceStub = this._gaxGrpc.createStub(
      this._opts.fallback
        ? (this._protos as protobuf.Root).lookupService(
            'google.cloud.sql.v1beta4.SqlWorkloadCapturesService',
          )
        : // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this._protos as any).google.cloud.sql.v1beta4
            .SqlWorkloadCapturesService,
      this._opts,
      this._providedCustomServicePath,
    ) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const sqlWorkloadCapturesServiceStubMethods = [
      'start',
      'stop',
      'startReplay',
      'stopReplay',
      'list',
    ];
    for (const methodName of sqlWorkloadCapturesServiceStubMethods) {
      const callPromise = this.sqlWorkloadCapturesServiceStub.then(
        stub =>
          (...args: Array<{}>) => {
            if (this._terminated) {
              return Promise.reject('The client has already been closed.');
            }
            const func = stub[methodName];
            return func.apply(stub, args);
          },
        (err: Error | null | undefined) => () => {
          throw err;
        },
      );

      const descriptor = undefined;
      const apiCall = this._gaxModule.createApiCall(
        callPromise,
        this._defaults[methodName],
        descriptor,
        this._opts.fallback,
      );

      this.innerApiCalls[methodName] = apiCall;
    }

    return this.sqlWorkloadCapturesServiceStub;
  }

  /**
   * The DNS address for this API service.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get servicePath() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static servicePath is deprecated, please use the instance method instead.',
        'DeprecationWarning',
      );
    }
    return 'sqladmin.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get apiEndpoint() {
    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      process.emitWarning(
        'Static apiEndpoint is deprecated, please use the instance method instead.',
        'DeprecationWarning',
      );
    }
    return 'sqladmin.googleapis.com';
  }

  /**
   * The DNS address for this API service.
   * @returns {string} The DNS address for this service.
   */
  get apiEndpoint() {
    return this._servicePath;
  }

  get universeDomain() {
    return this._universeDomain;
  }

  /**
   * The port for this API service.
   * @returns {number} The default port for this service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   * @returns {string[]} List of default scopes.
   */
  static get scopes() {
    return [
      'https://www.googleapis.com/auth/cloud-platform',
      'https://www.googleapis.com/auth/sqlservice.admin',
    ];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @returns {Promise} A promise that resolves to string containing the project ID.
   */
  getProjectId(
    callback?: Callback<string, undefined, undefined>,
  ): Promise<string> | void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  /**
   * Starts capturing the SQL queries, transactions, and other operations
   * executed on the primary instance. This traffic is securely stored and forms
   * a "captured workload". This workload can be replayed later on a different
   * instance to safely test performance impacts, database upgrades,
   * configuration changes etc. before applying them to production.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Required. Project ID of the project that contains the instance.
   * @param {string} request.instance
   *   Required. Cloud SQL instance ID. This does not include the project ID.
   * @param {google.cloud.sql.v1beta4.StartWorkloadCaptureContext} [request.startWorkloadCaptureContext]
   *   Optional. Contains details about the start workload capture operation.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.Operation|Operation}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/sql_workload_captures_service.start.js</caption>
   * region_tag:sqladmin_v1beta4_generated_SqlWorkloadCapturesService_Start_async
   */
  start(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  start(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  start(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  start(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        project: request.project ?? '',
        instance: request.instance ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('start request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('start response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .start(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IOperation,
          (
            | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('start response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }
  /**
   * Stops capturing the query traffic and related operations executed on the
   * primary instance.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Required. Project ID of the project that contains the instance.
   * @param {string} request.instance
   *   Required. Cloud SQL instance ID. This does not include the project ID.
   * @param {google.cloud.sql.v1beta4.StopWorkloadCaptureContext} [request.stopWorkloadCaptureContext]
   *   Optional. Contains details about the stop workload capture operation.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.Operation|Operation}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/sql_workload_captures_service.stop.js</caption>
   * region_tag:sqladmin_v1beta4_generated_SqlWorkloadCapturesService_Stop_async
   */
  stop(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  stop(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  stop(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  stop(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        project: request.project ?? '',
        instance: request.instance ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('stop request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('stop response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .stop(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IOperation,
          (
            | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('stop response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }
  /**
   * Starts executing a captured workload on a separate Cloud SQL instance
   * provisioned for workload replay. This target instance simulates the
   * production environment without affecting the primary instance.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Required. Project ID of the project that contains the instance.
   * @param {string} request.instance
   *   Required. Cloud SQL instance ID. This does not include the project ID.
   * @param {google.cloud.sql.v1beta4.StartWorkloadReplayContext} request.startWorkloadReplayContext
   *   Required. Contains details about the start workload replay operation.
   * @param {string} request.workloadId
   *   Required. The ID of the workload to replay.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.Operation|Operation}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/sql_workload_captures_service.start_replay.js</caption>
   * region_tag:sqladmin_v1beta4_generated_SqlWorkloadCapturesService_StartReplay_async
   */
  startReplay(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  startReplay(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  startReplay(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  startReplay(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        project: request.project ?? '',
        instance: request.instance ?? '',
        workload_id: request.workloadId?.toString() ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('startReplay request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('startReplay response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .startReplay(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IOperation,
          (
            | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStartReplayRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('startReplay response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }
  /**
   * Stops an active workload replay on the target Cloud SQL replay instance.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Required. Project ID of the project that contains the target replay
   *   instance.
   * @param {string} request.instance
   *   Required. Cloud SQL instance ID of the target replay instance. This does
   *   not include the project ID.
   * @param {google.cloud.sql.v1beta4.StopWorkloadReplayContext} [request.stopWorkloadReplayContext]
   *   Optional. Contains details about the stop workload replay operation.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.Operation|Operation}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/sql_workload_captures_service.stop_replay.js</caption>
   * region_tag:sqladmin_v1beta4_generated_SqlWorkloadCapturesService_StopReplay_async
   */
  stopReplay(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  stopReplay(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  stopReplay(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  stopReplay(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IOperation,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IOperation,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        project: request.project ?? '',
        instance: request.instance ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('stopReplay request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IOperation,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('stopReplay response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .stopReplay(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IOperation,
          (
            | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesStopReplayRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('stopReplay response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }
  /**
   * Lists all captured workloads associated with the instance.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Required. Project ID of the project that contains the instance.
   * @param {string} request.instance
   *   Required. Cloud SQL instance ID. This does not include the project ID.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link protos.google.cloud.sql.v1beta4.WorkloadCapturesListResponse|WorkloadCapturesListResponse}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example <caption>include:samples/generated/v1beta4/sql_workload_captures_service.list.js</caption>
   * region_tag:sqladmin_v1beta4_generated_SqlWorkloadCapturesService_List_async
   */
  list(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest,
    options?: CallOptions,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
        | undefined
      ),
      {} | undefined,
    ]
  >;
  list(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest,
    options: CallOptions,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  list(
    request: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest,
    callback: Callback<
      protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): void;
  list(
    request?: protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest,
    optionsOrCallback?:
      | CallOptions
      | Callback<
          protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
      | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<
    [
      protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
      (
        | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
        | undefined
      ),
      {} | undefined,
    ]
  > | void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers['x-goog-request-params'] =
      this._gaxModule.routingHeader.fromParams({
        project: request.project ?? '',
        instance: request.instance ?? '',
      });
    this.initialize().catch(err => {
      throw err;
    });
    this._log.info('list request %j', request);
    const wrappedCallback:
      | Callback<
          protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
          | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
          | null
          | undefined,
          {} | null | undefined
        >
      | undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('list response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls
      .list(request, options, wrappedCallback)
      ?.then(
        ([response, options, rawResponse]: [
          protos.google.cloud.sql.v1beta4.IWorkloadCapturesListResponse,
          (
            | protos.google.cloud.sql.v1beta4.ISqlWorkloadCapturesListRequest
            | undefined
          ),
          {} | undefined,
        ]) => {
          this._log.info('list response %j', response);
          return [response, options, rawResponse];
        },
      )
      .catch((error: any) => {
        if (
          error &&
          'statusDetails' in error &&
          error.statusDetails instanceof Array
        ) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(
            jsonProtos,
          ) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(
            error.statusDetails,
            protos,
          );
        }
        throw error;
      });
  }

  /**
   * Gets information about a location.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Resource name for the location.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html | CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing {@link google.cloud.location.Location | Location}.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
   *   for more details and examples.
   * @example
   * ```
   * const [response] = await client.getLocation(request);
   * ```
   */
  getLocation(
    request: LocationProtos.google.cloud.location.IGetLocationRequest,
    options?:
      | gax.CallOptions
      | Callback<
          LocationProtos.google.cloud.location.ILocation,
          | LocationProtos.google.cloud.location.IGetLocationRequest
          | null
          | undefined,
          {} | null | undefined
        >,
    callback?: Callback<
      LocationProtos.google.cloud.location.ILocation,
      | LocationProtos.google.cloud.location.IGetLocationRequest
      | null
      | undefined,
      {} | null | undefined
    >,
  ): Promise<LocationProtos.google.cloud.location.ILocation> {
    return this.locationsClient.getLocation(request, options, callback);
  }
  /**
   * Lists information about the supported locations for this service. Returns an iterable object.
   *
   * `for`-`await`-`of` syntax is used with the iterable to get response elements on-demand.
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   The resource that owns the locations collection, if applicable.
   * @param {string} request.filter
   *   The standard list filter.
   * @param {number} request.pageSize
   *   The standard list page size.
   * @param {string} request.pageToken
   *   The standard list page token.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Object}
   *   An iterable Object that allows {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols | async iteration }.
   *   When you iterate the returned iterable, each element will be an object representing
   *   {@link google.cloud.location.Location | Location}. The API will be called under the hood as needed, once per the page,
   *   so you can stop the iteration when you don't need more results.
   *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
   *   for more details and examples.
   * @example
   * ```
   * const iterable = client.listLocationsAsync(request);
   * for await (const response of iterable) {
   *   // process response
   * }
   * ```
   */
  listLocationsAsync(
    request: LocationProtos.google.cloud.location.IListLocationsRequest,
    options?: CallOptions,
  ): AsyncIterable<LocationProtos.google.cloud.location.ILocation> {
    return this.locationsClient.listLocationsAsync(request, options);
  }

  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified backup resource name string.
   *
   * @param {string} project
   * @param {string} backup
   * @returns {string} Resource name string.
   */
  backupPath(project: string, backup: string) {
    return this.pathTemplates.backupPathTemplate.render({
      project: project,
      backup: backup,
    });
  }

  /**
   * Parse the project from Backup resource.
   *
   * @param {string} backupName
   *   A fully-qualified path representing Backup resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromBackupName(backupName: string) {
    return this.pathTemplates.backupPathTemplate.match(backupName).project;
  }

  /**
   * Parse the backup from Backup resource.
   *
   * @param {string} backupName
   *   A fully-qualified path representing Backup resource.
   * @returns {string} A string representing the backup.
   */
  matchBackupFromBackupName(backupName: string) {
    return this.pathTemplates.backupPathTemplate.match(backupName).backup;
  }

  /**
   * Return a fully-qualified blueGreenDeployment resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} blue_green_deployment
   * @returns {string} Resource name string.
   */
  blueGreenDeploymentPath(
    project: string,
    location: string,
    blueGreenDeployment: string,
  ) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.render({
      project: project,
      location: location,
      blue_green_deployment: blueGreenDeployment,
    });
  }

  /**
   * Parse the project from BlueGreenDeployment resource.
   *
   * @param {string} blueGreenDeploymentName
   *   A fully-qualified path representing BlueGreenDeployment resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromBlueGreenDeploymentName(blueGreenDeploymentName: string) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.match(
      blueGreenDeploymentName,
    ).project;
  }

  /**
   * Parse the location from BlueGreenDeployment resource.
   *
   * @param {string} blueGreenDeploymentName
   *   A fully-qualified path representing BlueGreenDeployment resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromBlueGreenDeploymentName(blueGreenDeploymentName: string) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.match(
      blueGreenDeploymentName,
    ).location;
  }

  /**
   * Parse the blue_green_deployment from BlueGreenDeployment resource.
   *
   * @param {string} blueGreenDeploymentName
   *   A fully-qualified path representing BlueGreenDeployment resource.
   * @returns {string} A string representing the blue_green_deployment.
   */
  matchBlueGreenDeploymentFromBlueGreenDeploymentName(
    blueGreenDeploymentName: string,
  ) {
    return this.pathTemplates.blueGreenDeploymentPathTemplate.match(
      blueGreenDeploymentName,
    ).blue_green_deployment;
  }

  /**
   * Terminate the gRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   * @returns {Promise} A promise that resolves when the client is closed.
   */
  close(): Promise<void> {
    if (this.sqlWorkloadCapturesServiceStub && !this._terminated) {
      return this.sqlWorkloadCapturesServiceStub.then(stub => {
        this._log.info('ending gRPC channel');
        this._terminated = true;
        stub.close();
        this.locationsClient.close().catch(err => {
          throw err;
        });
      });
    }
    return Promise.resolve();
  }
}
