// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import {describe, it} from 'mocha';
import * as bluegreendeploymentsserviceModule from '../src';

import {PassThrough} from 'stream';

import {protobuf, LocationProtos} from 'google-gax';

// Dynamically loaded proto JSON is needed to get the type information
// to fill in default values for request objects
const root = protobuf.Root.fromJSON(
  require('../protos/protos.json'),
).resolveAll();

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function getTypeDefaultValue(typeName: string, fields: string[]) {
  let type = root.lookupType(typeName) as protobuf.Type;
  for (const field of fields.slice(0, -1)) {
    type = type.fields[field]?.resolvedType as protobuf.Type;
  }
  return type.fields[fields[fields.length - 1]]?.defaultValue;
}

function generateSampleMessage<T extends object>(instance: T) {
  const filledObject = (
    instance.constructor as typeof protobuf.Message
  ).toObject(instance as protobuf.Message<T>, {defaults: true});
  return (instance.constructor as typeof protobuf.Message).fromObject(
    filledObject,
  ) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
  return error
    ? sinon.stub().rejects(error)
    : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(
  response?: ResponseType,
  error?: Error,
) {
  return error
    ? sinon.stub().callsArgWith(2, error)
    : sinon.stub().callsArgWith(2, null, response);
}

function stubPageStreamingCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error,
) {
  const pagingStub = sinon.stub();
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
    }
  }
  const transformStub = error
    ? sinon.stub().callsArgWith(2, error)
    : pagingStub;
  const mockStream = new PassThrough({
    objectMode: true,
    transform: transformStub,
  });
  // trigger as many responses as needed
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      setImmediate(() => {
        mockStream.write({});
      });
    }
    setImmediate(() => {
      mockStream.end();
    });
  } else {
    setImmediate(() => {
      mockStream.write({});
    });
    setImmediate(() => {
      mockStream.end();
    });
  }
  return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error,
) {
  let counter = 0;
  const asyncIterable = {
    [Symbol.asyncIterator]() {
      return {
        async next() {
          if (error) {
            return Promise.reject(error);
          }
          if (counter >= responses!.length) {
            return Promise.resolve({done: true, value: undefined});
          }
          return Promise.resolve({done: false, value: responses![counter++]});
        },
      };
    },
  };
  return sinon.stub().returns(asyncIterable);
}

describe('v1beta4.BlueGreenDeploymentsServiceClient', () => {
  describe('Common methods', () => {
    it('has apiEndpoint', () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient();
      const apiEndpoint = client.apiEndpoint;
      assert.strictEqual(apiEndpoint, 'sqladmin.googleapis.com');
    });

    it('has universeDomain', () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient();
      const universeDomain = client.universeDomain;
      assert.strictEqual(universeDomain, 'googleapis.com');
    });

    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      it('throws DeprecationWarning if static servicePath is used', () => {
        const stub = sinon.stub(process, 'emitWarning');
        const servicePath =
          bluegreendeploymentsserviceModule.v1beta4
            .BlueGreenDeploymentsServiceClient.servicePath;
        assert.strictEqual(servicePath, 'sqladmin.googleapis.com');
        assert(stub.called);
        stub.restore();
      });

      it('throws DeprecationWarning if static apiEndpoint is used', () => {
        const stub = sinon.stub(process, 'emitWarning');
        const apiEndpoint =
          bluegreendeploymentsserviceModule.v1beta4
            .BlueGreenDeploymentsServiceClient.apiEndpoint;
        assert.strictEqual(apiEndpoint, 'sqladmin.googleapis.com');
        assert(stub.called);
        stub.restore();
      });
    }
    it('sets apiEndpoint according to universe domain camelCase', () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {universeDomain: 'example.com'},
        );
      const servicePath = client.apiEndpoint;
      assert.strictEqual(servicePath, 'sqladmin.example.com');
    });

    it('sets apiEndpoint according to universe domain snakeCase', () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {universe_domain: 'example.com'},
        );
      const servicePath = client.apiEndpoint;
      assert.strictEqual(servicePath, 'sqladmin.example.com');
    });

    if (typeof process === 'object' && 'env' in process) {
      describe('GOOGLE_CLOUD_UNIVERSE_DOMAIN environment variable', () => {
        it('sets apiEndpoint from environment variable', () => {
          const saved = process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = 'example.com';
          const client =
            new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient();
          const servicePath = client.apiEndpoint;
          assert.strictEqual(servicePath, 'sqladmin.example.com');
          if (saved) {
            process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = saved;
          } else {
            delete process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          }
        });

        it('value configured in code has priority over environment variable', () => {
          const saved = process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = 'example.com';
          const client =
            new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
              {universeDomain: 'configured.example.com'},
            );
          const servicePath = client.apiEndpoint;
          assert.strictEqual(servicePath, 'sqladmin.configured.example.com');
          if (saved) {
            process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = saved;
          } else {
            delete process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          }
        });
      });
    }
    it('does not allow setting both universeDomain and universe_domain', () => {
      assert.throws(() => {
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {universe_domain: 'example.com', universeDomain: 'example.net'},
        );
      });
    });

    it('has port', () => {
      const port =
        bluegreendeploymentsserviceModule.v1beta4
          .BlueGreenDeploymentsServiceClient.port;
      assert(port);
      assert(typeof port === 'number');
    });

    it('should create a client with no option', () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient();
      assert(client);
    });

    it('should create a client with gRPC fallback', () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            fallback: true,
          },
        );
      assert(client);
    });

    it('has initialize method and supports deferred initialization', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      assert.strictEqual(client.blueGreenDeploymentsServiceStub, undefined);
      await client.initialize();
      assert(client.blueGreenDeploymentsServiceStub);
    });

    it('has close method for the initialized client', done => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      client.initialize().catch(err => {
        throw err;
      });
      assert(client.blueGreenDeploymentsServiceStub);
      client
        .close()
        .then(() => {
          done();
        })
        .catch(err => {
          throw err;
        });
    });

    it('has close method for the non-initialized client', done => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      assert.strictEqual(client.blueGreenDeploymentsServiceStub, undefined);
      client
        .close()
        .then(() => {
          done();
        })
        .catch(err => {
          throw err;
        });
    });

    it('has getProjectId method', async () => {
      const fakeProjectId = 'fake-project-id';
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
      const result = await client.getProjectId();
      assert.strictEqual(result, fakeProjectId);
      assert((client.auth.getProjectId as SinonStub).calledWithExactly());
    });

    it('has getProjectId method with callback', async () => {
      const fakeProjectId = 'fake-project-id';
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      client.auth.getProjectId = sinon
        .stub()
        .callsArgWith(0, null, fakeProjectId);
      const promise = new Promise((resolve, reject) => {
        client.getProjectId((err?: Error | null, projectId?: string | null) => {
          if (err) {
            reject(err);
          } else {
            resolve(projectId);
          }
        });
      });
      const result = await promise;
      assert.strictEqual(result, fakeProjectId);
    });
  });

  describe('createBlueGreenDeployment', () => {
    it('invokes createBlueGreenDeployment without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.Operation(),
      );
      client.innerApiCalls.createBlueGreenDeployment =
        stubSimpleCall(expectedResponse);
      const [response] = await client.createBlueGreenDeployment(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.createBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createBlueGreenDeployment without error using callback', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.Operation(),
      );
      client.innerApiCalls.createBlueGreenDeployment =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.createBlueGreenDeployment(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.sql.v1beta4.IOperation | null,
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          },
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.createBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createBlueGreenDeployment with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.createBlueGreenDeployment = stubSimpleCall(
        undefined,
        expectedError,
      );
      await assert.rejects(
        client.createBlueGreenDeployment(request),
        expectedError,
      );
      const actualRequest = (
        client.innerApiCalls.createBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createBlueGreenDeployment with closed client', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.CreateBlueGreenDeploymentRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close().catch(err => {
        throw err;
      });
      await assert.rejects(
        client.createBlueGreenDeployment(request),
        expectedError,
      );
    });
  });

  describe('getBlueGreenDeployment', () => {
    it('invokes getBlueGreenDeployment without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
      );
      client.innerApiCalls.getBlueGreenDeployment =
        stubSimpleCall(expectedResponse);
      const [response] = await client.getBlueGreenDeployment(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.getBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getBlueGreenDeployment without error using callback', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
      );
      client.innerApiCalls.getBlueGreenDeployment =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.getBlueGreenDeployment(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.sql.v1beta4.IBlueGreenDeployment | null,
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          },
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.getBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getBlueGreenDeployment with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.getBlueGreenDeployment = stubSimpleCall(
        undefined,
        expectedError,
      );
      await assert.rejects(
        client.getBlueGreenDeployment(request),
        expectedError,
      );
      const actualRequest = (
        client.innerApiCalls.getBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getBlueGreenDeployment with closed client', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.GetBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close().catch(err => {
        throw err;
      });
      await assert.rejects(
        client.getBlueGreenDeployment(request),
        expectedError,
      );
    });
  });

  describe('switchoverBlueGreenDeployment', () => {
    it('invokes switchoverBlueGreenDeployment without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.Operation(),
      );
      client.innerApiCalls.switchoverBlueGreenDeployment =
        stubSimpleCall(expectedResponse);
      const [response] = await client.switchoverBlueGreenDeployment(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.switchoverBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.switchoverBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes switchoverBlueGreenDeployment without error using callback', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.Operation(),
      );
      client.innerApiCalls.switchoverBlueGreenDeployment =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.switchoverBlueGreenDeployment(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.sql.v1beta4.IOperation | null,
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          },
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.switchoverBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.switchoverBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes switchoverBlueGreenDeployment with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.switchoverBlueGreenDeployment = stubSimpleCall(
        undefined,
        expectedError,
      );
      await assert.rejects(
        client.switchoverBlueGreenDeployment(request),
        expectedError,
      );
      const actualRequest = (
        client.innerApiCalls.switchoverBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.switchoverBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes switchoverBlueGreenDeployment with closed client', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.SwitchoverBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close().catch(err => {
        throw err;
      });
      await assert.rejects(
        client.switchoverBlueGreenDeployment(request),
        expectedError,
      );
    });
  });

  describe('deleteBlueGreenDeployment', () => {
    it('invokes deleteBlueGreenDeployment without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.Operation(),
      );
      client.innerApiCalls.deleteBlueGreenDeployment =
        stubSimpleCall(expectedResponse);
      const [response] = await client.deleteBlueGreenDeployment(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.deleteBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteBlueGreenDeployment without error using callback', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.Operation(),
      );
      client.innerApiCalls.deleteBlueGreenDeployment =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.deleteBlueGreenDeployment(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.sql.v1beta4.IOperation | null,
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          },
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.deleteBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteBlueGreenDeployment with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1 ?? ''}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.deleteBlueGreenDeployment = stubSimpleCall(
        undefined,
        expectedError,
      );
      await assert.rejects(
        client.deleteBlueGreenDeployment(request),
        expectedError,
      );
      const actualRequest = (
        client.innerApiCalls.deleteBlueGreenDeployment as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteBlueGreenDeployment as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteBlueGreenDeployment with closed client', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.DeleteBlueGreenDeploymentRequest',
        ['name'],
      );
      request.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close().catch(err => {
        throw err;
      });
      await assert.rejects(
        client.deleteBlueGreenDeployment(request),
        expectedError,
      );
    });
  });

  describe('listBlueGreenDeployments', () => {
    it('invokes listBlueGreenDeployments without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
      ];
      client.innerApiCalls.listBlueGreenDeployments =
        stubSimpleCall(expectedResponse);
      const [response] = await client.listBlueGreenDeployments(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.listBlueGreenDeployments as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.listBlueGreenDeployments as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes listBlueGreenDeployments without error using callback', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
      ];
      client.innerApiCalls.listBlueGreenDeployments =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.listBlueGreenDeployments(
          request,
          (
            err?: Error | null,
            result?:
              protos.google.cloud.sql.v1beta4.IBlueGreenDeployment[] | null,
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          },
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.listBlueGreenDeployments as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.listBlueGreenDeployments as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes listBlueGreenDeployments with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.listBlueGreenDeployments = stubSimpleCall(
        undefined,
        expectedError,
      );
      await assert.rejects(
        client.listBlueGreenDeployments(request),
        expectedError,
      );
      const actualRequest = (
        client.innerApiCalls.listBlueGreenDeployments as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.listBlueGreenDeployments as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes listBlueGreenDeploymentsStream without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
      ];
      client.descriptors.page.listBlueGreenDeployments.createStream =
        stubPageStreamingCall(expectedResponse);
      const stream = client.listBlueGreenDeploymentsStream(request);
      const promise = new Promise((resolve, reject) => {
        const responses: protos.google.cloud.sql.v1beta4.BlueGreenDeployment[] =
          [];
        stream.on(
          'data',
          (response: protos.google.cloud.sql.v1beta4.BlueGreenDeployment) => {
            responses.push(response);
          },
        );
        stream.on('end', () => {
          resolve(responses);
        });
        stream.on('error', (err: Error) => {
          reject(err);
        });
      });
      const responses = await promise;
      assert.deepStrictEqual(responses, expectedResponse);
      assert(
        (
          client.descriptors.page.listBlueGreenDeployments
            .createStream as SinonStub
        )
          .getCall(0)
          .calledWith(client.innerApiCalls.listBlueGreenDeployments, request),
      );
      assert(
        (
          client.descriptors.page.listBlueGreenDeployments
            .createStream as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams,
          ),
      );
    });

    it('invokes listBlueGreenDeploymentsStream with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedError = new Error('expected');
      client.descriptors.page.listBlueGreenDeployments.createStream =
        stubPageStreamingCall(undefined, expectedError);
      const stream = client.listBlueGreenDeploymentsStream(request);
      const promise = new Promise((resolve, reject) => {
        const responses: protos.google.cloud.sql.v1beta4.BlueGreenDeployment[] =
          [];
        stream.on(
          'data',
          (response: protos.google.cloud.sql.v1beta4.BlueGreenDeployment) => {
            responses.push(response);
          },
        );
        stream.on('end', () => {
          resolve(responses);
        });
        stream.on('error', (err: Error) => {
          reject(err);
        });
      });
      await assert.rejects(promise, expectedError);
      assert(
        (
          client.descriptors.page.listBlueGreenDeployments
            .createStream as SinonStub
        )
          .getCall(0)
          .calledWith(client.innerApiCalls.listBlueGreenDeployments, request),
      );
      assert(
        (
          client.descriptors.page.listBlueGreenDeployments
            .createStream as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams,
          ),
      );
    });

    it('uses async iteration with listBlueGreenDeployments without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
        generateSampleMessage(
          new protos.google.cloud.sql.v1beta4.BlueGreenDeployment(),
        ),
      ];
      client.descriptors.page.listBlueGreenDeployments.asyncIterate =
        stubAsyncIterationCall(expectedResponse);
      const responses: protos.google.cloud.sql.v1beta4.IBlueGreenDeployment[] =
        [];
      const iterable = client.listBlueGreenDeploymentsAsync(request);
      for await (const resource of iterable) {
        responses.push(resource!);
      }
      assert.deepStrictEqual(responses, expectedResponse);
      assert.deepStrictEqual(
        (
          client.descriptors.page.listBlueGreenDeployments
            .asyncIterate as SinonStub
        ).getCall(0).args[1],
        request,
      );
      assert(
        (
          client.descriptors.page.listBlueGreenDeployments
            .asyncIterate as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams,
          ),
      );
    });

    it('uses async iteration with listBlueGreenDeployments with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest(),
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.sql.v1beta4.ListBlueGreenDeploymentsRequest',
        ['parent'],
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1 ?? ''}`;
      const expectedError = new Error('expected');
      client.descriptors.page.listBlueGreenDeployments.asyncIterate =
        stubAsyncIterationCall(undefined, expectedError);
      const iterable = client.listBlueGreenDeploymentsAsync(request);
      await assert.rejects(async () => {
        const responses: protos.google.cloud.sql.v1beta4.IBlueGreenDeployment[] =
          [];
        for await (const resource of iterable) {
          responses.push(resource!);
        }
      });
      assert.deepStrictEqual(
        (
          client.descriptors.page.listBlueGreenDeployments
            .asyncIterate as SinonStub
        ).getCall(0).args[1],
        request,
      );
      assert(
        (
          client.descriptors.page.listBlueGreenDeployments
            .asyncIterate as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams,
          ),
      );
    });
  });
  describe('getLocation', () => {
    it('invokes getLocation without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.GetLocationRequest(),
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new LocationProtos.google.cloud.location.Location(),
      );
      client.locationsClient.getLocation = stubSimpleCall(expectedResponse);
      const response = await client.getLocation(request, expectedOptions);
      assert.deepStrictEqual(response, [expectedResponse]);
      assert(
        (client.locationsClient.getLocation as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined),
      );
    });
    it('invokes getLocation without error using callback', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.GetLocationRequest(),
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new LocationProtos.google.cloud.location.Location(),
      );
      client.locationsClient.getLocation = sinon
        .stub()
        .callsArgWith(2, null, expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.getLocation(
          request,
          expectedOptions,
          (
            err?: Error | null,
            result?: LocationProtos.google.cloud.location.ILocation | null,
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          },
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert((client.locationsClient.getLocation as SinonStub).getCall(0));
    });
    it('invokes getLocation with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.GetLocationRequest(),
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.locationsClient.getLocation = stubSimpleCall(
        undefined,
        expectedError,
      );
      await assert.rejects(
        client.getLocation(request, expectedOptions),
        expectedError,
      );
      assert(
        (client.locationsClient.getLocation as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined),
      );
    });
  });
  describe('listLocationsAsync', () => {
    it('uses async iteration with listLocations without error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.ListLocationsRequest(),
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedResponse = [
        generateSampleMessage(
          new LocationProtos.google.cloud.location.Location(),
        ),
        generateSampleMessage(
          new LocationProtos.google.cloud.location.Location(),
        ),
        generateSampleMessage(
          new LocationProtos.google.cloud.location.Location(),
        ),
      ];
      client.locationsClient.descriptors.page.listLocations.asyncIterate =
        stubAsyncIterationCall(expectedResponse);
      const responses: LocationProtos.google.cloud.location.ILocation[] = [];
      const iterable = client.listLocationsAsync(request);
      for await (const resource of iterable) {
        responses.push(resource!);
      }
      assert.deepStrictEqual(responses, expectedResponse);
      assert.deepStrictEqual(
        (
          client.locationsClient.descriptors.page.listLocations
            .asyncIterate as SinonStub
        ).getCall(0).args[1],
        request,
      );
      assert(
        (
          client.locationsClient.descriptors.page.listLocations
            .asyncIterate as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams,
          ),
      );
    });
    it('uses async iteration with listLocations with error', async () => {
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.ListLocationsRequest(),
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedError = new Error('expected');
      client.locationsClient.descriptors.page.listLocations.asyncIterate =
        stubAsyncIterationCall(undefined, expectedError);
      const iterable = client.listLocationsAsync(request);
      await assert.rejects(async () => {
        const responses: LocationProtos.google.cloud.location.ILocation[] = [];
        for await (const resource of iterable) {
          responses.push(resource!);
        }
      });
      assert.deepStrictEqual(
        (
          client.locationsClient.descriptors.page.listLocations
            .asyncIterate as SinonStub
        ).getCall(0).args[1],
        request,
      );
      assert(
        (
          client.locationsClient.descriptors.page.listLocations
            .asyncIterate as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams,
          ),
      );
    });
  });

  describe('Path templates', () => {
    describe('backup', async () => {
      const fakePath = '/rendered/path/backup';
      const expectedParameters = {
        project: 'projectValue',
        backup: 'backupValue',
      };
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      client.pathTemplates.backupPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.backupPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('backupPath', () => {
        const result = client.backupPath('projectValue', 'backupValue');
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.backupPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters),
        );
      });

      it('matchProjectFromBackupName', () => {
        const result = client.matchProjectFromBackupName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.backupPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath),
        );
      });

      it('matchBackupFromBackupName', () => {
        const result = client.matchBackupFromBackupName(fakePath);
        assert.strictEqual(result, 'backupValue');
        assert(
          (client.pathTemplates.backupPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath),
        );
      });
    });

    describe('blueGreenDeployment', async () => {
      const fakePath = '/rendered/path/blueGreenDeployment';
      const expectedParameters = {
        project: 'projectValue',
        location: 'locationValue',
        blue_green_deployment: 'blueGreenDeploymentValue',
      };
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      client.pathTemplates.blueGreenDeploymentPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.blueGreenDeploymentPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('blueGreenDeploymentPath', () => {
        const result = client.blueGreenDeploymentPath(
          'projectValue',
          'locationValue',
          'blueGreenDeploymentValue',
        );
        assert.strictEqual(result, fakePath);
        assert(
          (
            client.pathTemplates.blueGreenDeploymentPathTemplate
              .render as SinonStub
          )
            .getCall(-1)
            .calledWith(expectedParameters),
        );
      });

      it('matchProjectFromBlueGreenDeploymentName', () => {
        const result = client.matchProjectFromBlueGreenDeploymentName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (
            client.pathTemplates.blueGreenDeploymentPathTemplate
              .match as SinonStub
          )
            .getCall(-1)
            .calledWith(fakePath),
        );
      });

      it('matchLocationFromBlueGreenDeploymentName', () => {
        const result =
          client.matchLocationFromBlueGreenDeploymentName(fakePath);
        assert.strictEqual(result, 'locationValue');
        assert(
          (
            client.pathTemplates.blueGreenDeploymentPathTemplate
              .match as SinonStub
          )
            .getCall(-1)
            .calledWith(fakePath),
        );
      });

      it('matchBlueGreenDeploymentFromBlueGreenDeploymentName', () => {
        const result =
          client.matchBlueGreenDeploymentFromBlueGreenDeploymentName(fakePath);
        assert.strictEqual(result, 'blueGreenDeploymentValue');
        assert(
          (
            client.pathTemplates.blueGreenDeploymentPathTemplate
              .match as SinonStub
          )
            .getCall(-1)
            .calledWith(fakePath),
        );
      });
    });

    describe('location', async () => {
      const fakePath = '/rendered/path/location';
      const expectedParameters = {
        project: 'projectValue',
        location: 'locationValue',
      };
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      client.pathTemplates.locationPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.locationPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('locationPath', () => {
        const result = client.locationPath('projectValue', 'locationValue');
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.locationPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters),
        );
      });

      it('matchProjectFromLocationName', () => {
        const result = client.matchProjectFromLocationName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.locationPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath),
        );
      });

      it('matchLocationFromLocationName', () => {
        const result = client.matchLocationFromLocationName(fakePath);
        assert.strictEqual(result, 'locationValue');
        assert(
          (client.pathTemplates.locationPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath),
        );
      });
    });

    describe('project', async () => {
      const fakePath = '/rendered/path/project';
      const expectedParameters = {
        project: 'projectValue',
      };
      const client =
        new bluegreendeploymentsserviceModule.v1beta4.BlueGreenDeploymentsServiceClient(
          {
            credentials: {client_email: 'bogus', private_key: 'bogus'},
            projectId: 'bogus',
          },
        );
      await client.initialize();
      client.pathTemplates.projectPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.projectPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('projectPath', () => {
        const result = client.projectPath('projectValue');
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.projectPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters),
        );
      });

      it('matchProjectFromProjectName', () => {
        const result = client.matchProjectFromProjectName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.projectPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath),
        );
      });
    });
  });
});
